In [2]:
# import proper libraries
import numpy as np
from hmmlearn import hmm

#
np.random.seed(42)

In [5]:
model = hmm.GaussianHMM(n_components=3, covariance_type="full")
model.startprob_ = np.array([0.6, 0.3, 0.1])
model.transmat_  = np.array([[0.7, 0.2, 0.1],
                             [0.3, 0.5, 0.2],
                             [0.3, 0.3, 0.4]])
model.means_  = np.array([[0.0, 0.0], [3.0, -3.0], [5.0, 10.0]])
model.covars_ = np.tile(np.identity(2), (3, 1, 1))
print(model.means_)
print(np.tile(np.identity(2), (3, 1, 1)))

[[ 0.  0.]
 [ 3. -3.]
 [ 5. 10.]]
[[[1. 0.]
  [0. 1.]]

 [[1. 0.]
  [0. 1.]]

 [[1. 0.]
  [0. 1.]]]


In [4]:
X, Z = model.sample(100)
print(X)

[[-1.11188012e+00  3.18902185e-01]
 [ 1.57921282e+00  7.67434729e-01]
 [-5.80878134e-01 -5.25169807e-01]
 [ 2.41962272e-01 -1.91328024e+00]
 [ 8.16445081e-01 -1.52387600e+00]
 [-9.08024076e-01 -1.41230370e+00]
 [-6.29474961e-01  5.97720467e-01]
 [-5.44382725e-01  1.10922590e-01]
 [-6.00253850e-01  9.47439821e-01]
 [-6.01706612e-01  1.85227818e+00]
 [-5.33648804e-01 -5.52786232e-03]
 [ 5.82254491e+00  8.77915635e+00]
 [ 5.77831304e+00 -1.80636028e+00]
 [ 7.38466580e-01  1.71368281e-01]
 [-1.00908534e+00 -1.58329421e+00]
 [-4.60638771e-01  1.05712223e+00]
 [-1.13055230e+00  1.34428883e-01]
 [ 2.32307800e+00 -2.38832371e+00]
 [ 5.82122795e-01  8.87748460e-01]
 [ 2.16078248e+00 -3.30921238e+00]
 [ 3.49184671e+00  1.10996470e+01]
 [-1.10633497e+00 -1.19620662e+00]
 [ 3.83479542e+00 -2.70343862e+00]
 [ 3.36163603e+00 -3.64511975e+00]
 [ 4.49543425e+00 -2.66181875e+00]
 [ 3.80254896e-01 -2.17809750e+00]
 [-1.41875046e+00  1.04249162e+00]
 [-2.19671888e-01  3.57112572e-01]
 [-7.89258329e-01  7

In [7]:
remodel = hmm.GaussianHMM(n_components=3, covariance_type="full", n_iter=100)
remodel.fit(X)  

GaussianHMM(algorithm='viterbi', covariance_type='full', covars_prior=0.01,
      covars_weight=1, init_params='stmc', means_prior=0, means_weight=0,
      min_covar=0.001, n_components=3, n_iter=100, params='stmc',
      random_state=None, startprob_prior=1.0, tol=0.01, transmat_prior=1.0,
      verbose=False)

In [8]:
Z2 = remodel.predict(X)
print(Z2)

[0 0 0 0 0 0 0 0 0 0 0 1 2 0 0 0 0 2 0 2 1 0 2 2 2 0 0 0 0 0 1 1 1 1 0 2 2
 2 2 1 0 0 0 0 0 0 0 0 0 0 0 0 1 1 2 1 2 1 1 0 0 0 2 2 2 2 1 1 2 2 1 1 1 2
 2 1 1 1 1 1 1 1 2 2 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0]
